/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/C9MlqH9JFdK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function ContactInformation() {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-gradient-to-b from-[#f0f8ff] to-[#e6f2ff]">
      <header className="w-full bg-white shadow-sm">
        <div className="container mx-auto flex items-center justify-between px-4 py-4 md:px-6">
          <nav className="flex items-center gap-6">
            <Link href="#" className="font-medium hover:underline" prefetch={false}>
              Take quiz
            </Link>
            <Link href="#" className="font-medium hover:underline" prefetch={false}>
              Skin Basics
            </Link>
            <Link href="#" className="font-medium hover:underline" prefetch={false}>
              Products
            </Link>
            <Link href="#" className="font-medium hover:underline" prefetch={false}>
              Our Story
            </Link>
          </nav>
          <div>
            <Link href="#" className="text-lg font-medium hover:underline" prefetch={false}>
              <UserIcon className="h-6 w-6" />
            </Link>
          </div>
        </div>
      </header>
      <main className="flex-1 flex items-center justify-center px-4 py-12 md:px-6">
        <div className="max-w-md w-full space-y-6">
          <h1 className="text-4xl font-bold text-center">Get personalized skincare recommendations</h1>
          <p className="text-lg text-center text-muted-foreground">Enter your name and email to get started.</p>
          <form className="space-y-4">
            <div>
              <Label htmlFor="name" className="sr-only">
                Name
              </Label>
              <Input
                id="name"
                type="text"
                placeholder="Your name"
                className="rounded-full px-4 py-3 border border-input focus:border-primary focus:ring-primary"
              />
            </div>
            <div>
              <Label htmlFor="email" className="sr-only">
                Email
              </Label>
              <Input
                id="email"
                type="email"
                placeholder="Your email"
                className="rounded-full px-4 py-3 border border-input focus:border-primary focus:ring-primary"
              />
            </div>
            <Button
              type="submit"
              className="w-full rounded-full bg-primary text-primary-foreground px-6 py-3 font-medium hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            >
              NEXT
            </Button>
          </form>
        </div>
      </main>
    </div>
  )
}

function UserIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
